### ISSUE TITLE
blog post not appearing... again

### ISSUE THREAD

**Issue by MonicaUnlimited** [MonicaUnlimited/Your-Pitta-is-Too-Damn-High#1]
:tired_face:
@AlexChambers
I cant figure out why the blog post are not showing. I'm giving up today. I did my best.
:weary:

**Comment by MonicaUnlimited** [comment]
@jonabc
it's happening here as well.  the blog post is not appearing.  i will change both to minima theme and see what happens.
:unamused:

**Comment by MonicaUnlimited** [comment]
minima theme already applied on this one.

**Comment by jonabc** [comment]
@MonicaUnlimited 

I _think_ the problem on this one is that you're including a full HTML document in [index.html](https://github.com/MonicaUnlimited/Your-Pitta-is-Too-Damn-High/blob/gh-pages/index.html).  What happens if you remove the `<html>`, `<head>` and `<body>` tags?

I'm pretty sure you can specify the page title by copy / pasting this to the top of index.html
```
---
title: "Your Pitta is Too Damn High!"
---
```

**Comment by MonicaUnlimited** [comment]
@jonabc will test now

**Comment by MonicaUnlimited** [comment]
i will update the index.html to index.md
thank you jon :ok_hand:

**Comment by MonicaUnlimited** [comment]
@jonabc :star: :star: :star:  My hero! Thanks again! 
i will check why ## Social Good Ipsum is not appearing as a header.

**Comment by MonicaUnlimited** [comment]
closing this issue.  Thanks again! :thumbsup:
